In [8]:
f2 = open("./test1.txt", "w")
f2.write("\n여기 업데이트")
f2.close()


In [5]:
f = open("./member.txt", "w")
f.close()

for i in range(1, 4):
    f = open("./member.txt", "a")
    name = input("이름 >")
    pwd  = input("패스워드 >")
    f.write(f"\n이름 = {name}\n패스워드 = {pwd}\n----------------")
    f.close()

f = open("member.txt", "r")
print(f.read())
f.close()



이름 = 김김
패스워드 = 김김
----------------
이름 = 유유
패스워드 = 유유
----------------
이름 = 사사
패스워드 = 사사
----------------


In [ ]:
def set_member_tel(user, phon_num, l):
    f = open("./member_tel.txt", "r")
    
    if user not in l:
        l.append(f"이름 = {user}\n전화번호 = {phon_num}\n------------------------")
    else :
        idx = l.index(user)
        l.remove(f"이름 = {user}\n전화번호 = {phon_num}\n------------------------")
        l.insert(idx, f"이름 = {user}\n전화번호 = {phon_num}\n------------------------")
    
    for sub in len(l):
        str +=sub

    f.write(str)
    f.close()
    

l = list()

while True:
    user = input("이름을 입력하세요.")
    pw = input("비밀번호를 입력하세요.")

    f = open("./member.txt", "r")

    find = f"이름 = {user}\n패스워드 = {pw}"
    str = f.read()

    if find in str:
        print("로그인 성공")
        phon_num = input("전화번호를 입력하세요.")
        set_member_tel(user, phon_num, l)
        break
    else :
        print("로그인 실패")

    f.close()


In [53]:
import numpy as np

print("실습1번")
a = np.zeros(10)
print(a)

print("실습2번")
a[5]=1
print(a)

print("실습3번")
b = np.arange(10, 31)
print(b)

print("실습4번")
c = np.random.randint(0, 100, size=(2,2))
print(c)

print("실습5번")
d = np.random.rand(2, 4)
print(d)

print("실습6번")
e = np.arange(35, 75)
e = e.reshape(10, 4)
print(e)

print("실습7번")
len(e)
for i in range(len(e)-1, -1, -1):
    print(e[i])

print("실습8번")
print(e[1:len(e)-2, 2:])


print("실습9번")
x = e[0:len(e), 3]
print(x)
x = x.reshape(10, 1)
print(x)

print("실습10번")
print(x[::-1])

print("실습11번")
y = np.random.randint(1, 51, size=(5,6))
print(y)
print("짝수만 출력")
print(y[y%2==0])



실습1번
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
실습2번
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
실습3번
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
실습4번
[[28 54]
 [93 61]]
실습5번
[[0.90365934 0.5589468  0.19259559 0.99381356]
 [0.45175755 0.08841692 0.29872648 0.43617403]]
실습6번
[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
실습7번
[71 72 73 74]
[67 68 69 70]
[63 64 65 66]
[59 60 61 62]
[55 56 57 58]
[51 52 53 54]
[47 48 49 50]
[43 44 45 46]
[39 40 41 42]
[35 36 37 38]
실습8번
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]]
실습9번
[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
실습10번
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
실습11번
[[47 18 18 30 13 41]
 [ 1 18  6 28 26 21]
 [27 10 49  4 37 29]
 [44 31 16 31  7 27]
 [48  7  2 31 39  6]]
짝수만 출력
[18 18 30 18  6 28 26 10  4 44 16 48  2  6]
